// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:a8eb8101-712d-4983-a9a9-536fdd07e2a1",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_owwb2qU39",
    "aws_user_pools_web_client_id": "3aniobmsv328asrv54pct5tn0j",
    "aws_appsync_graphqlEndpoint": "https://hdznug3o3rg5baws3jyogycxye.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
